import javascript from "@eslint/js";
import reactHooks from "eslint-plugin-react-hooks";
import typescriptEslint from "typescript-eslint";

export default typescriptEslint.config(
  {
    ignores: [
      ".react-router/**",
      "build/**",
      "node_modules/**",
      "app/graphql/graphqlEnvironment.d.ts",
    ],
  },
  javascript.configs.recommended,
  typescriptEslint.configs.recommended,
  reactHooks.configs.flat["recommended-latest"],
  {
    files: ["**/*.ts", "**/*.tsx"],
    languageOptions: {
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    rules: {
      "no-undef": "off",
      "no-console": ["error", { allow: ["warn", "error"] }],
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { disallowTypeAnnotations: false },
      ],
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "id-denylist": [
        "error",
        "arr",
        "btn",
        "cfg",
        "col",
        "ctx",
        "cur",
        "curr",
        "db",
        "desc",
        "dir",
        "doc",
        "el",
        "elem",
        "env",
        "err",
        "evt",
        "ev",
        "fn",
        "idx",
        "img",
        "impl",
        "info",
        "init",
        "len",
        "lib",
        "msg",
        "num",
        "obj",
        "opt",
        "opts",
        "param",
        "prev",
        "prod",
        "prop",
        "qty",
        "req",
        "res",
        "resp",
        "ret",
        "src",
        "str",
        "temp",
        "tmp",
        "util",
        "utils",
        "val",
        "var",
        "vars",
      ],
    },
  },
);
