<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Zappy.Adapters.GraphQL</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HotChocolate.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Zappy.Application\Zappy.Application.csproj" />
  </ItemGroup>

</Project>
